name: Update README with Latest Blog Posts

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch: # ← Обязательно! Без этого нет ручного запуска

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0 # Важно для коммитов

      - name: Fetch blog posts from Dev.to
        uses: gautamkrishnar/blog-post-workflow@v1.9
        with:
          max_post_count: "4"
          feed_list: "https://dev.to/feed/medvedev013" # 🔥 ЗАМЕНИТЕ НА СВОЙ НИК!
          template: |
            <!-- BLOG-POST-LIST:START -->
            ## 📝 Latest Articles

            {{#each posts}}
            - [{{title}}]({{link}}) — _{{date}}_
            {{/each}}
            <!-- BLOG-POST-LIST:END -->

      - name: Check for changes and commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          if git diff --cached --quiet; then
            echo "✅ No changes detected. README is up to date."
          else
            git commit -m "chore: update README with latest blog posts"
            git push
            echo "✅ README updated successfully!"
          fi